version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ycFQIfJhcrYmSzRttCvIdbXgddQjLlPV
      MYSQL_DATABASE: railway
      MYSQL_USER: root
      MYSQL_PASSWORD: ycFQIfJhcrYmSzRttCvIdbXgddQjLlPV
    ports:
      - "3306:3306"   # 호스트와 컨테이너의 포트를 3306으로 설정
  springboot-app:
    build: .
    ports:
      - "8080:8080"   # Spring Boot 애플리케이션의 포트를 8090으로 설정
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql.railway.internal:3306/railway
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ycFQIfJhcrYmSzRttCvIdbXgddQjLlPV