/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2025-04-13 01:13:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Workspace/GoroGoroCommunity/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GoroGoroCommunity/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1744161964722L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"image/favicon.png\">\r\n");
      out.write("<!-- Bootstrap CDN -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("js/validation.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction signIn() {\r\n");
      out.write("\t\tlocation.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("member/signIn\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 1. 회원가입 완료버튼 누르고, 회원가입 \r\n");
      out.write("\tfunction signUpProcess() {\r\n");
      out.write("\r\n");
      out.write("\t\tvar email = $(\"#email\").val(); // 이메일(아이디)\r\n");
      out.write("\t\tvar nick = $(\"#nick\").val(); // 대화명\r\n");
      out.write("\t\tvar question = $(\"#question\").val(); // 질문\r\n");
      out.write("\t\tvar answer = $(\"#answer\").val(); // 답\r\n");
      out.write("\t\tvar passwords = $(\"#passwords\").val(); // 비밀번호1\r\n");
      out.write("\t\tvar passwordsConfirm = $(\"#passwordsConfirm\").val(); //비밀번호2 \r\n");
      out.write("\r\n");
      out.write("\t\tvar emailValidity = RegExp(/^[A-Za-z0-9_\\.\\-]+@[A-Za-z0-9\\-]+\\.[A-Za-z0-9\\-]+/); //이메일 유효성 검사\r\n");
      out.write("\r\n");
      out.write("\t\tvar formData = new FormData($('#signUpMemberDTO')[0]);\r\n");
      out.write("\r\n");
      out.write("\t\tif (email == \"\") {\r\n");
      out.write("\t\t\talert(\"이메일을 입력해주세요.\");\r\n");
      out.write("\t\t\t$(\"#email\").focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (nick == \"\") {\r\n");
      out.write("\t\t\talert(\"닉네임을 입력해주세요.\");\r\n");
      out.write("\t\t\t$(\"#nick\").focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (passwords == \"\" || passwordsConfirm == \"\") {\r\n");
      out.write("\t\t\talert(\"패스워드를 입력해주세요.\");\r\n");
      out.write("\t\t\t$(\"#passwords\").focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tvar yn = confirm(\"회원가입을 하시겠습니까?\");\r\n");
      out.write("\r\n");
      out.write("\t\tif (yn) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tif ((passwords == passwordsConfirm) && (emailValidity.test($(\"#email\").val()))) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("member/checkEmail\",\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tdata : {email : email},\r\n");
      out.write("\t\t\t\t\tsuccess :\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tfunction(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tif (data == \"unavailable\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"이미 그 아이디는 누가 사용하고 있기에 사용불가입니다. \");\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t// 입력한 이메일이 중복된 이메일이 아니기에 사용가능하다면, \t\r\n");
      out.write("\t\t\t\t\t\t\t} else if (data == \"available\") {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t// 닉네임 중복검사\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("member/checkNick\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata : {nick : nick},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsuccess :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfunction(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tif (data == \"unavailable\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\talert(\"입력하신 닉네임은 이미 누가 사용중이기에 사용할 수 없습니다. 다른 닉네임을 입력해주세요! \");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t// 사용가능 한 닉네임이라면,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t} else if (data == \"available\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t// 회원가입 진행한다. \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("member/signUpProcess\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata : formData,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tcache : false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tasync : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tcontentType : false, //이것을 붙이고 나서 업로드가 된것이다. \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tprocessData : false, // 이것을 붙이고 업로드가 되었다. \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tsuccess : function(obj) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tif (obj != null) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar result = obj.result;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tif (result == \"success\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talert(\"회원가입을 성공하였습니다. 로그인 페이지로 이동하겠습니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsignIn();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talert(\"회원가입에 실패하였습니다. \");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\terror : function(request, status, error) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talert(\"code:\" + request.status + \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"\\n\" + \"message:\" + request.responseText + \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"\\n\" + \"error:\" + error);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t}) // 회원가입 아작스의 끝\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t} // 사용가능한 닉네임 체크여부 else if의 끝\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t} // 닉네임 체크 function(data)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t})// 닉네임 중복 아작스\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t} // 이메일 중복 체크 아작스 \r\n");
      out.write("\t\t\t\t\t\t} // 이메일 중복체크 function(data)\r\n");
      out.write("\t\t\t\t\t})// 이메일 중복 아작스\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t} else if (passwords != passwordsConfirm) {\r\n");
      out.write("\t\t\t\talert(\"패스워드는 같아야합니다.\");\r\n");
      out.write("\t\t\t} else if (!emailValidity.test($(\"#email\").val())) {\r\n");
      out.write("\t\t\t\talert(\"이메일 형식에 맞게 입력을 해주시고 다시한번 회원가입 시도해주세요!\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t}//yn의 끝\r\n");
      out.write("\t} //signUpProcess()의 끝\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("/* 슬라이더 영역 CSS */\r\n");
      out.write(".slider img{ display:block; width:100%; max-width:100%; height:300px; }\r\n");
      out.write("body{ background-color: white; }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 메뉴부분 -->\r\n");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!--가운데 그림-->\r\n");
      out.write("<article class=\"slider\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("image/Camping.jpg\"></article>\r\n");
      out.write("<!-- 회원가입 폼 -->\r\n");
      out.write("<div class=\"container\" style=\"margin-top:50px; margin-bottom:50px;\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-sm-3\"></div>\r\n");
      out.write("\t\t<div class=\"col-sm-7\"><h4>회원가입</h4>\r\n");
      out.write("\t\t<div class=\"card shadow-none\">\r\n");
      out.write("\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t<form name=\"signUpMemberDTO\" method=\"post\" id=\"signUpMemberDTO\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>이메일(E-mail address)</td>\r\n");
      out.write("\t  \t\t\t\t<td>\r\n");
      out.write("\t  \t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t  \t\t\t\t\t\t<input type=\"email\" id=\"email\" name=\"email\" class=\"form-control\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<font id=\"checkId\" size=\"2\"></font>\r\n");
      out.write("\t  \t\t\t\t</td>\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t \t \t\t\t<td>비밀번호</td>\r\n");
      out.write("\t  \t\t\t\t<td><input type=\"password\" name=\"passwords\" id=\"passwords\" class=\"form-control pw\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>↑ 위 비밀번호 확인</td>\r\n");
      out.write("\t  \t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"passwordsConfirm\" id=\"passwordsConfirm\" class=\"form-control pw\"/>\r\n");
      out.write("\t\t\t\t\t\t<font id=\"checkPw\" size=\"2\"></font>\r\n");
      out.write("\t  \t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>닉네임</td>\r\n");
      out.write("\t  \t\t\t\t<td>\r\n");
      out.write("\t  \t\t\t\t\t<input type=\"text\" id=\"nick\" name=\"nick\" class=\"form-control\">\r\n");
      out.write("\t  \t\t\t\t\t<font id=\"checkNick\" size=\"2\"></font>\r\n");
      out.write("\t  \t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>이메일 또는 비밀번호 분실시 질문&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"question\" id=\"question\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"당신의 고향은 어디입니까?\">당신의 고향은 어디입니까?</option>\r\n");
      out.write("    \t\t\t\t\t\t<option value=\"별명은 무엇인가요?\">별명은 무엇인가요? </option>\r\n");
      out.write("    \t\t\t\t\t\t<option value=\"첫 사랑은 누구인가요?\">첫 사랑은 누구인가요?</option>\r\n");
      out.write("    \t\t\t\t\t\t<option value=\"애완동물의 이름은?\">애완동물의 이름은?</option>\r\n");
      out.write("    \t\t\t\t\t\t<option value=\"당신의 보물1호는 무엇인가요?\">당신의 보물1호는 무엇인가요?</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>↑ 위 질문에 대한 답</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"answer\" id=\"answer\" class=\"form-control\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t  \t\t\t\t<td colspan = \"2\" align = \"center\">\r\n");
      out.write("\t  \t\t\t\t\t<div class=\"text-right\" style=\"margin-top:50px; margin-bottom:50px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-danger\" onclick=\"javascript:signUpProcess();\">회원가입 완료</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t  \t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\t// 비밀번호와 확인용 비밀번호의 일치여부 체크\r\n");
      out.write("\t$('.pw').focusout(function() {\r\n");
      out.write("\r\n");
      out.write("\t\tlet isPassOk = false;\r\n");
      out.write("\r\n");
      out.write("\t\tlet passwords = $(\"#passwords\").val();\r\n");
      out.write("\t\tlet passwordsConfirm = $(\"#passwordsConfirm\").val();\r\n");
      out.write("\r\n");
      out.write("\t\tif (passwords != \"\" && passwordsConfirm != \"\") {\r\n");
      out.write("\t\t\tif (passwords == passwordsConfirm) {\r\n");
      out.write("\t\t\t\tlet isPassOk = true;\r\n");
      out.write("\t\t\t\t$(\"#checkPw\").html('비밀번호가 일치합니다. ');\r\n");
      out.write("\t\t\t\t$(\"#checkPw\").attr('color', 'green');\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tlet isPassOk = false;\r\n");
      out.write("\t\t\t\t$(\"#checkPw\").html('불일치 합니다. 다시한번 확인해주세요!');\r\n");
      out.write("\t\t\t\t$(\"#checkPw\").attr('color', 'red');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\t// 아이디용 이메일 검사\r\n");
      out.write("\t$(\"#email\").keyup(\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar emailValidity = RegExp(/^[A-Za-z0-9_\\.\\-]+@[A-Za-z0-9\\-]+\\.[A-Za-z0-9\\-]+/);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t//이메일 유효성 검사\r\n");
      out.write("\t\t\t\tif (!emailValidity.test($(\"#email\").val())) { //이메일 형식에 맞지않는경우, \r\n");
      out.write("\t\t\t\t\t$(\"#checkId\").html('이메일형식에 맞게 입력해주세요.');\r\n");
      out.write("\t\t\t\t\t$(\"#checkId\").attr('color', 'red');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("member/checkEmail\",\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tdata : {email : $(\"#email\").val()},\r\n");
      out.write("\t\t\t\t\tsuccess : \r\n");
      out.write("\t\t\t\t\t\tfunction(data) {\r\n");
      out.write("\t\t\t\t\t\t\tif (data == \"unavailable\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#checkId\").html('아이디 중복');\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#checkId\").attr('color', 'red');\r\n");
      out.write("\t\t\t\t\t\t\t} else if (data == \"available\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#checkId\").html('아이디 사용가능');\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#checkId\").attr('color', 'green');\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t// 닉네임 중복검사\r\n");
      out.write("\t$(\"#nick\").blur(\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction() { //foucusout, keyup, change, blur\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("member/checkNick\",\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tdata : {nick : $(\"#nick\").val()},\r\n");
      out.write("\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\tif (result == \"unavailable\") {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#checkNick\").html('중복된 닉네임! 사용불가');\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#checkNick\").attr('color', 'red');\r\n");
      out.write("\t\t\t\t\t\t} else if (result == \"available\") {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#checkNick\").html('사용가능합니다.');\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#checkNick\").attr('color', 'green');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-sm-3\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 하단 -->\r\n");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/view/member/signUp.jsp(3,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("root");
      // /WEB-INF/view/member/signUp.jsp(3,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/member/signUp.jsp(3,0) '${pageContext.request.contextPath }/'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }/",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/view/member/signUp.jsp(151,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("/WEB-INF/view/include/topMenu.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/view/member/signUp.jsp(298,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("/WEB-INF/view/include/bottomInfo.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }
}
